### ISSUE TITLE
[Firefox 55][Kassi Share - Send to Kodi v4.0] "Connection Failed" On settings dialog

### ISSUE THREAD

**Issue by rechapit** [goldenratio/youtube-to-XBMC#4]
While trying to configure the addon I get a "Connection failed" message.
Tested with Kodi 17.3. Kodi's web inteface is accessible and the original "Send to XBMC/Kodi" works fine in the same configuration

**Comment by goldenratio** [comment]
![screenshot000](https://user-images.githubusercontent.com/3019293/28751437-389a1dce-7510-11e7-91cb-3086623542ff.png)

Make sure "Allow remote control via HTTP" is enabled. Can be found under service settings.

If you still have issue, attach kodi logs and Kassi share's settings browser console logs.

**Comment by rechapit** [comment]
HTTP is enabled.
Like I mentioned in the original report other similar addon is working when this one isn't.
Please reopen the issue.

**Comment by rechapit** [comment]
I have made come debugging of my own:
When the save button is pressed the addon attempt to POST a JSON.
I tried the POST manually and it gets a response
![1](https://user-images.githubusercontent.com/4292607/28753923-a53d360e-7511-11e7-8ec4-46e0f52e305a.jpg)
However the addon either does not parse the response properly or cannot complete the request at all for some reason.
Permissions issues maybe?

**Comment by rechapit** [comment]
Maybe is related to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1344465)?

**Comment by goldenratio** [comment]
open kassi share settings page and open dev console (press F12) and click "console" tab. And click "save" button in settings page.
Send me the console info.

Example: 
![image](https://user-images.githubusercontent.com/3019293/28754174-02e1063c-7549-11e7-8c85-0cca639fe493.png)

**Comment by rechapit** [comment]
Just this:
<< JSONRPC.Ping Object { jsonrpc: "2.0", method: "JSONRPC.Ping", id: 1 }  shared.js:74:13
"this.kodiConf.url http://raspberrypi:8080/jsonrpc"  shared.js:79:13

**Comment by goldenratio** [comment]
you need to figured out why kodi is not sending any response back. 
In kassi settings page, open dev tools (F12) and open networks tab and check what is happening.

**Comment by rechapit** [comment]
Debugging didn't reveal much, as far as I could tell an exception is thrown every time a request is attempted but could not get much data out of it.So I tried sniffing with wireshark and I find out the request never makes it out.
However, as I found out, this might be a [bug a in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1344465) and the addon might have nothing to do with it.

**Comment by goldenratio** [comment]
works fine for me, using firefox too.

**Comment by goldenratio** [comment]
> exception is thrown every time a request is attempted

what exception?

**Comment by rechapit** [comment]
Sorry I took so long to reply.
Console says "uncaught exception: undefined".
Problem is still present in FF55
However I don't think is a problem with the addon itself. So far I haven't been able to use any webextension addon that makes HTTP request. They all fail in similar fashion.

**Comment by goldenratio** [comment]
line number?

**Comment by rechapit** [comment]
shared.js:83 invoked at settings.js:268

**Comment by rechapit** [comment]
Looks I found a bug/unintended feature in [uMatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/). Since webextensions are more similar to web pages than regular plugins they get affected by uMatrix configuration, and all request get intercepted and ran through umatrix's rules. If the plugin is not given explicit permission, it will not be able to access kodi's url.
So yeah. Plugin is working. Sorry about all the fuss
