### ISSUE TITLE
After YouTube redesign large boxes are displayed

### ISSUE THREAD

**Issue by honyczek** [goldenratio/youtube-to-XBMC#5]
![image](https://user-images.githubusercontent.com/1797918/29907800-e67e261c-8e1d-11e7-83b0-1a4fe8befff6.png)

I use Google Chrome 60.0.3112.113 + Kassi Share 5.1 and today I see a new design of YouTube. Kassi Share plugin's boxes with links _Play now | [+] Add to queue_ are displayed in video suggestions next to video previews, instead of below the picture.

**Comment by goldenratio** [comment]
Ya, it is a known issue. It is hard inject links in youtube's new design, because new design makes use of web components. I will see if I can do something about it.

**Comment by goldenratio** [comment]
Decided to remove in-page links for now. It is hard to add them nicely in youtube's new polymer based design.
If anyone wants to help, PRs are welcome.
