### ISSUE TITLE
Doesn't works in openload

### ISSUE THREAD

**Issue by RobertusIT** [goldenratio/youtube-to-XBMC#6]
Hi, i tried your ext, but in openload doesn't works.

Is possible have it also with openload?

**Comment by goldenratio** [comment]
What is openload?

**Comment by RobertusIT** [comment]
Video streaming

Il 11 ott 2017 16:03, "Karthik VJ" <notifications@github.com> ha scritto:

> What is openload?
>
>

**Comment by goldenratio** [comment]
sorry, not possible.

**Comment by RobertusIT** [comment]
Oh I see, I ask it because in rapid video works, and is another streaming
web site

Il 11 ott 2017 20:49, "Karthik VJ" <notifications@github.com> ha scritto:
