### ISSUE TITLE
Kassi Share stuck on loading

### ISSUE THREAD

**Issue by matiasw** [goldenratio/youtube-to-XBMC#7]
Hi,
I have been using Kassi Share successfully with my Kodi 17.6, but recently, it has stopped working. Now, when I try to use it with eg. a Youtube video, it seems to send the video to Kodi successfully, because a loading spinner appears on the Kodi screen, but nothing happens after that. 
In my browser, Opera 57.0.3098.116, the extension settings show "Connection Success!", and when I click the "Play Now" button, the spinner appears, so I think the connection works, but after that, I am just stuck with the spinner. After a very long time, I get the error message from Kodi: "Playback failed. One or more items failed to play. Check the log for more information about this message". There is nothing in the Kodi logs about why the video does not play like is used to.

What should I do?

**Comment by bazoombaboomba** [comment]
Got a similar problem and i needed to restart Kodi, then it worked again. Not sure why this happens, but i can livbe with it, because it is only every 2-3 weeks.

**Comment by goldenratio** [comment]
@matiasw I tested with Openelec 8.0.4 (which is Kodi 17.3)  and Kodi 18 seems to work fine

Can you try reinstalling youtube addon on your Kodi?

**Comment by matiasw** [comment]
I rebooted LibreELEC a few times and it worked again. So, it seems sporadic.
